name: drugis.org - home of the ADDIS project
markdown: kramdown
highlighter: pygments
url: http://drugis.org
rss_path: /news
rss_name: rss.xml
rss_post_limit: 10
paginate: 5
paginate_path: "/news/page:num"
permalink: /:year-:month-:day-:title.html
plugins: [jekyll-paginate, jekyll-sass-converter, jekyll/scholar]

scholar:
  style: ./_bibliography/apa.csl
  bibliography: publications
  bibliography_template: bibentry

authors:
  gert:
    display_name: Gert van Valkenhoef
  daan:
    display_name: Daan Reid
