name: drugis.org - home of the ADDIS project
markdown: redcarpet
pygments: true
url: http://drugis.org
rss_path: /news
rss_name: rss.xml
rss_post_limit: 10
paginate: 5
paginate_path: "news/page:num"
permalink: /:year-:month-:day-:title.html

scholar:
  style: ./_bibliography/apa.csl
  bibliography: publications

authors:
  gert:
    display_name: Gert van Valkenhoef
